application: aebootcamp-mckoss
version: data
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images
  
- url: /styles
  static_dir: styles
  
- url: /scripts
  static_dir: scripts

- url: /favicon.ico
  static_files: images/favicon.ico
  upload: images/favicon.ico

- url: /robots.txt
  static_files: files/robots.txt
  upload: files/robots.txt

# Remote access to the datastore, using remote_console.py
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

# Python Shell for administrative tasks
# See http://code.google.com/p/google-app-engine-samples/source/browse/trunk/shell
- url: /shell
  script: shell.py
  login: admin
  
# For Google Webmaster Tools domain validation
# TODO: Get your own file name from webmaster tools
- url: /google9eab28331a1ab405.html
  static_files: static/google9eab28331a1ab405.html
  upload: static/google9eab28331a1ab405.html
  
- url: /.*
  script: main.py

skip_files: |
 ^(.*/)?(
 ([Tt]humbs\.db)|
 (app\.yaml)|
 (app\.yml)|
 (index\.yaml)|
 (index\.yml)|
 (#.*#)|
 (.*~)|
 (.*\.bak)|
 (.*\.psd)|
 (.*\.ai)|
 (.*\.py[co])|
 (.*/RCS/.*)|
 (\..*)|
 )$
